### ISSUE TITLE
[BORK] Bossbar doesnt update on claim until changing a setting.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#15] opened 2020-08-08 07:42 UTC
Reported by Devin in discord.
![image](https://user-images.githubusercontent.com/25861695/89705180-fec0b380-d90f-11ea-9b57-608dafcdfe7e.png)

**Comment by Ph4i1ur3** [comment] 2020-08-17 13:15
Unable to reproduce

**Comment by Ph4i1ur3** [comment] 2020-08-19 18:35
Closing this, as it doesn't appear to be a current bug

**Closed by Ph4i1ur3** 2020-08-19 18:35 UTC
Labels: Research, Waiting for Response or Verification
