### ISSUE TITLE
[BORK] staff gets spammed when players go to spawn

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#67] opened 2020-08-18 11:28 UTC
> **Describe the bug**:
Every time someone goes to spawn it hits staff with a console message

> **How To Reproduce**:

have _anyone_ do ./spawn

> **Expected behavior**:
silence.

> **Screenshots**:

![image](https://user-images.githubusercontent.com/25861695/90507749-44009480-e10b-11ea-9470-4810a4fac694.png)

> **Additional context**:
its really annoying if 3 or 4 people go all at once

**Comment by Ph4i1ur3** [comment] 2020-08-18 17:36
https://github.com/Adriftus-Studios/network-script-data/blob/596e8d88828e5bc07e605a3cf77351d447c76990/denizen_scripts/survival/repo-link/spawn_scripts/survival_rtp.dsc#L81

This is the root cause

**Comment by Ph4i1ur3** [comment] 2020-08-19 14:38
Fixed by #74

**Closed by Ph4i1ur3** 2020-08-19 14:38 UTC
Labels: Help Wanted, To-Do
